name: my_movie_search
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  
  # Note: use "dart pub outdated" to find libraries that should be upgraded
  bloc: ^8.0.3
  
  cached_network_image: ^3.3.0          # preload large images
  cloud_firestore: ^4.9.1
  
  cupertino_icons: ^1.0.4               # iOS style icons.
  device_info_plus: ^9.1.1              # get infomation about the manufacturer of the phone
  easy_debounce: ^2.0.3                 # manage the frequency fo requests
  easy_image_viewer: ^1.2.1
  equatable: ^2.0.3                     # Simplify object comparisons.

  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  #firebase_ui_auth: ^1.7.0       # does not work on linux :(
  #firebase_core: ^1.0.3                # Firebase initialisation
  #firebase_auth: ^3.0.1                # Authenticate users against Firebase
  #cloud_firestore: ^2.4.0              # Store data in Firebase Firestore cloud database
  
  firedart: ^0.9.7                      # dart native wrapper to firebase API
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1                  # Assist with the BLoC design pattern.
  flutter_custom_tabs: ^1.0.4           # replace webview with andorid chrome browser
  flutter_dotenv: ^5.0.2                # Read secrests and settings from .env file.
  go_router: ^12.1.1                    # screen navigation
  grpc: ^3.2.4                          # extended firedart error handling
  html: ^0.15.0                         # Dart dom and html utilities.
  html_unescape: ^2.0.0                 # decode &apos;
  hydrated_bloc: ^9.1.2                 # automatic restoration for bloc data
  intl: ^0.18.0                         # internationalisation including number and data formatting.
  lint: ^2.0.1
  logger: ^2.0.2                        # Log trace messages to console.
  ####logger_flutter: ^0.7.1            # Shake device to see trace messages.
  meta: ^1.9.1                          # extended annotations
  path: ^1.8.0                          # File path manipulation library
  path_provider: ^2.0.9                 # Device filesystem access for accessing database files.

  provider: ^6.0.5                      # so ChangeNotifierProvider can notify change to firebase login state

  simple_barcode_scanner: ^0.0.8
  #sqflite: ^2.0.2                       # Database storage for persisting state across sessions.
  sqflite_common_ffi: ^2.3.2+1          # Database storage for persisting state across sessions.
  sqlite3_flutter_libs: ^0.5.20         # Database storage for persisting state across sessions.
  universal_io: ^2.0.4                  # Consistent environment variable fetching and CORS http gets across web&mobile platforms.
  url_launcher: ^6.0.20                 # for hyperlinks e.g. https://pub.dev/documentation/url_launcher/latest/link/Link-class.html
  webview_flutter: ^4.0.1               # Show web page


dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
   - assets/settings.json
   - assets/secrets.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  fonts:
     - family: Lato
       fonts: 
         - asset: fonts/Lato-Regular.ttf
         - asset: fonts/Lato-Black.ttf
           weight: 700
         - asset: fonts/Lato-BlackItalic.ttf
           weight: 700
           style: italic
         - asset: fonts/Lato-Italic.ttf
           style: italic
         - asset: fonts/Lato-Light.ttf
         - asset: fonts/Lato-LightItalic.ttf
           style: italic
         - asset: fonts/Lato-Thin.ttf
         - asset: fonts/Lato-ThinItalic.ttf
           style: italic



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
