name: my_movie_search
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Note: use "dart pub outdated" to find libraries that should be upgraded
  bloc: ^8.0.3
  equatable: ^2.0.3                     # Simplify object comparisons.
  flutter_bloc: ^8.0.1                  # Assist with the BLoC design pattern.
  flutter_custom_tabs: ^1.0.4           # replace webview with andorid chrome browser
  flutter_dotenv: ^5.0.2                # Read secrests and settings from .env file.
  html: ^0.15.0                         # Dart dom and html utilities.
  html_unescape: ^2.0.0                 # decode &apos;
  intl: ^0.17.0                         # internationalisation including number and data formatting.
  logger: ^1.1.0                        # Log trace messages to console.
  path_provider: ^2.0.9                  # Device filesystem access for accessing database files.
  path: ^1.8.0                           # File path manipulation library
  pinch_zoom_image_last: ^0.4.1         # pinch to zoom on images
  sqflite: ^2.0.2                       # Database storage for persisting state across sessions.
  ####logger_flutter: ^0.7.1            # Shake device to see trace messages.
  universal_io: ^2.0.4                  # Consistent environment variable fetching and CORS http gets across web&mobile platforms.
  url_launcher: ^6.0.20                  # for hyperlinks e.g. https://pub.dev/documentation/url_launcher/latest/link/Link-class.html
  webview_flutter: ^2.8.0                # Show web page (Note V3.0.0 availoable but needs testing)

  #firebase_core: ^1.0.3                # Firebase initialisation
  firebase_auth: ^3.0.1                 # Authenticate users against Firebase
  cloud_firestore: ^2.4.0               # Store data in Firebase Firestore cloud database


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  lint: ^1.8.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  fonts:
     - family: Lato
       fonts: 
         - asset: fonts/Lato-Regular.ttf
         - asset: fonts/Lato-Black.ttf
           weight: 700
         - asset: fonts/Lato-BlackItalic.ttf
           weight: 700
           style: italic
         - asset: fonts/Lato-Italic.ttf
           style: italic
         - asset: fonts/Lato-Light.ttf
         - asset: fonts/Lato-LightItalic.ttf
           style: italic
         - asset: fonts/Lato-Thin.ttf
         - asset: fonts/Lato-ThinItalic.ttf
           style: italic


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
assets:
  - assets/.env
  - assets/a.txt
  - a.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
