// Mocks generated by Mockito from annotations
// in my_movie_search/test/persistence/dto_cache_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_movie_search/movies/models/movie_result_dto.dart' as _i2;
import 'package:my_movie_search/persistence/tiered_cache.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMovieResultDTO_0 extends _i1.SmartFake
    implements _i2.MovieResultDTO {
  _FakeMovieResultDTO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TieredCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockTieredCache extends _i1.Mock
    implements _i3.TieredCache<_i2.MovieResultDTO> {
  @override
  Map<Object, _i2.MovieResultDTO> get memoryCache =>
      (super.noSuchMethod(
            Invocation.getter(#memoryCache),
            returnValue: <Object, _i2.MovieResultDTO>{},
            returnValueForMissingStub: <Object, _i2.MovieResultDTO>{},
          )
          as Map<Object, _i2.MovieResultDTO>);

  @override
  set memoryCache(Map<Object, _i2.MovieResultDTO>? value) => super.noSuchMethod(
    Invocation.setter(#memoryCache, value),
    returnValueForMissingStub: null,
  );

  @override
  void add(Object? key, _i2.MovieResultDTO? item) => super.noSuchMethod(
    Invocation.method(#add, [key, item]),
    returnValueForMissingStub: null,
  );

  @override
  void remove(Object? key) => super.noSuchMethod(
    Invocation.method(#remove, [key]),
    returnValueForMissingStub: null,
  );

  @override
  void clearMemoryOnly() => super.noSuchMethod(
    Invocation.method(#clearMemoryOnly, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isCached(Object? key) =>
      (super.noSuchMethod(
            Invocation.method(#isCached, [key]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  int cachedSize() =>
      (super.noSuchMethod(
            Invocation.method(#cachedSize, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i2.MovieResultDTO get(Object? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValue: _FakeMovieResultDTO_0(
              this,
              Invocation.method(#get, [key]),
            ),
            returnValueForMissingStub: _FakeMovieResultDTO_0(
              this,
              Invocation.method(#get, [key]),
            ),
          )
          as _i2.MovieResultDTO);

  @override
  void addToCacheList(Object? key, Object? item) => super.noSuchMethod(
    Invocation.method(#addToCacheList, [key, item]),
    returnValueForMissingStub: null,
  );
}
