// Mocks generated by Mockito 5.4.6 from annotations
// in my_movie_search/test/unit/base_movie_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:my_movie_search/movies/models/movie_result_dto.dart' as _i6;
import 'package:my_movie_search/movies/models/search_criteria_dto.dart' as _i4;
import 'package:my_movie_search/utilities/web_data/src/web_fetch_base.dart'
    as _i7;
import 'package:my_movie_search/utilities/web_data/src/web_fetch_limiter.dart'
    as _i2;
import 'package:universal_io/io.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWebFetchLimiter_0 extends _i1.SmartFake
    implements _i2.WebFetchLimiter {
  _FakeWebFetchLimiter_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_1 extends _i1.SmartFake implements Uri {
  _FakeUri_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClient_2 extends _i1.SmartFake implements _i3.HttpClient {
  _FakeHttpClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchCriteriaDTO].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchCriteriaDTO extends _i1.Mock implements _i4.SearchCriteriaDTO {
  @override
  String get searchId =>
      (super.noSuchMethod(
            Invocation.getter(#searchId),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#searchId),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#searchId),
            ),
          )
          as String);

  @override
  String get criteriaTitle =>
      (super.noSuchMethod(
            Invocation.getter(#criteriaTitle),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#criteriaTitle),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#criteriaTitle),
            ),
          )
          as String);

  @override
  _i4.SearchCriteriaType get criteriaType =>
      (super.noSuchMethod(
            Invocation.getter(#criteriaType),
            returnValue: _i4.SearchCriteriaType.none,
            returnValueForMissingStub: _i4.SearchCriteriaType.none,
          )
          as _i4.SearchCriteriaType);

  @override
  List<_i6.MovieResultDTO> get criteriaList =>
      (super.noSuchMethod(
            Invocation.getter(#criteriaList),
            returnValue: <_i6.MovieResultDTO>[],
            returnValueForMissingStub: <_i6.MovieResultDTO>[],
          )
          as List<_i6.MovieResultDTO>);

  @override
  set searchId(String? value) => super.noSuchMethod(
    Invocation.setter(#searchId, value),
    returnValueForMissingStub: null,
  );

  @override
  set criteriaTitle(String? value) => super.noSuchMethod(
    Invocation.setter(#criteriaTitle, value),
    returnValueForMissingStub: null,
  );

  @override
  set criteriaType(_i4.SearchCriteriaType? value) => super.noSuchMethod(
    Invocation.setter(#criteriaType, value),
    returnValueForMissingStub: null,
  );

  @override
  set criteriaContext(_i6.MovieResultDTO? value) => super.noSuchMethod(
    Invocation.setter(#criteriaContext, value),
    returnValueForMissingStub: null,
  );

  @override
  set criteriaList(List<_i6.MovieResultDTO>? value) => super.noSuchMethod(
    Invocation.setter(#criteriaList, value),
    returnValueForMissingStub: null,
  );

  @override
  String toJson({bool? includeRelated = true}) =>
      (super.noSuchMethod(
            Invocation.method(#toJson, [], {#includeRelated: includeRelated}),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#toJson, [], {#includeRelated: includeRelated}),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#toJson, [], {#includeRelated: includeRelated}),
            ),
          )
          as String);
}

/// A class which mocks [WebFetchBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebFetchBase<OUTPUT_TYPE, INPUT_TYPE> extends _i1.Mock
    implements _i7.WebFetchBase<OUTPUT_TYPE, INPUT_TYPE> {
  @override
  INPUT_TYPE get criteria =>
      (super.noSuchMethod(
            Invocation.getter(#criteria),
            returnValue: _i5.dummyValue<INPUT_TYPE>(
              this,
              Invocation.getter(#criteria),
            ),
            returnValueForMissingStub: _i5.dummyValue<INPUT_TYPE>(
              this,
              Invocation.getter(#criteria),
            ),
          )
          as INPUT_TYPE);

  @override
  _i2.WebFetchLimiter get searchResultsLimit =>
      (super.noSuchMethod(
            Invocation.getter(#searchResultsLimit),
            returnValue: _FakeWebFetchLimiter_0(
              this,
              Invocation.getter(#searchResultsLimit),
            ),
            returnValueForMissingStub: _FakeWebFetchLimiter_0(
              this,
              Invocation.getter(#searchResultsLimit),
            ),
          )
          as _i2.WebFetchLimiter);

  @override
  bool get transformJsonP =>
      (super.noSuchMethod(
            Invocation.getter(#transformJsonP),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get retryDelay =>
      (super.noSuchMethod(
            Invocation.getter(#retryDelay),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get maxDelay =>
      (super.noSuchMethod(
            Invocation.getter(#maxDelay),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i7.DataSourceFn get selectedDataSource =>
      (super.noSuchMethod(
            Invocation.getter(#selectedDataSource),
            returnValue: (dynamic s) => _i8.Future<_i8.Stream<String>>.value(
              _i8.Stream<String>.empty(),
            ),
            returnValueForMissingStub: (dynamic s) =>
                _i8.Future<_i8.Stream<String>>.value(
                  _i8.Stream<String>.empty(),
                ),
          )
          as _i7.DataSourceFn);

  @override
  String get getCriteriaText =>
      (super.noSuchMethod(
            Invocation.getter(#getCriteriaText),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#getCriteriaText),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#getCriteriaText),
            ),
          )
          as String);

  @override
  set criteria(INPUT_TYPE? value) => super.noSuchMethod(
    Invocation.setter(#criteria, value),
    returnValueForMissingStub: null,
  );

  @override
  set searchResultsLimit(_i2.WebFetchLimiter? value) => super.noSuchMethod(
    Invocation.setter(#searchResultsLimit, value),
    returnValueForMissingStub: null,
  );

  @override
  set transformJsonP(bool? value) => super.noSuchMethod(
    Invocation.setter(#transformJsonP, value),
    returnValueForMissingStub: null,
  );

  @override
  set retryDelay(int? value) => super.noSuchMethod(
    Invocation.setter(#retryDelay, value),
    returnValueForMissingStub: null,
  );

  @override
  set maxDelay(int? value) => super.noSuchMethod(
    Invocation.setter(#maxDelay, value),
    returnValueForMissingStub: null,
  );

  @override
  set selectedDataSource(_i7.DataSourceFn? value) => super.noSuchMethod(
    Invocation.setter(#selectedDataSource, value),
    returnValueForMissingStub: null,
  );

  @override
  void populateStream(
    _i8.StreamController<OUTPUT_TYPE>? sc, {
    _i7.DataSourceFn? source,
    int? limit,
  }) => super.noSuchMethod(
    Invocation.method(#populateStream, [sc], {#source: source, #limit: limit}),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<List<OUTPUT_TYPE>> readList({
    _i7.DataSourceFn? source,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readList, [], {#source: source, #limit: limit}),
            returnValue: _i8.Future<List<OUTPUT_TYPE>>.value(<OUTPUT_TYPE>[]),
            returnValueForMissingStub: _i8.Future<List<OUTPUT_TYPE>>.value(
              <OUTPUT_TYPE>[],
            ),
          )
          as _i8.Future<List<OUTPUT_TYPE>>);

  @override
  _i8.Future<List<OUTPUT_TYPE>> readCachedList({
    _i7.DataSourceFn? source,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readCachedList, [], {
              #source: source,
              #limit: limit,
            }),
            returnValue: _i8.Future<List<OUTPUT_TYPE>>.value(<OUTPUT_TYPE>[]),
            returnValueForMissingStub: _i8.Future<List<OUTPUT_TYPE>>.value(
              <OUTPUT_TYPE>[],
            ),
          )
          as _i8.Future<List<OUTPUT_TYPE>>);

  @override
  _i8.Future<Iterable<OUTPUT_TYPE>> myConvertTreeToOutputType(
    dynamic listOrMapOrDocument,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#myConvertTreeToOutputType, [
              listOrMapOrDocument,
            ]),
            returnValue: _i8.Future<Iterable<OUTPUT_TYPE>>.value(
              <OUTPUT_TYPE>[],
            ),
            returnValueForMissingStub: _i8.Future<Iterable<OUTPUT_TYPE>>.value(
              <OUTPUT_TYPE>[],
            ),
          )
          as _i8.Future<Iterable<OUTPUT_TYPE>>);

  @override
  _i8.Future<List<dynamic>> myConvertWebTextToTraversableTree(
    String? webText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#myConvertWebTextToTraversableTree, [webText]),
            returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
            returnValueForMissingStub: _i8.Future<List<dynamic>>.value(
              <dynamic>[],
            ),
          )
          as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<_i8.Stream<String>> myConvertCriteriaToWebText() =>
      (super.noSuchMethod(
            Invocation.method(#myConvertCriteriaToWebText, []),
            returnValue: _i8.Future<_i8.Stream<String>>.value(
              _i8.Stream<String>.empty(),
            ),
            returnValueForMissingStub: _i8.Future<_i8.Stream<String>>.value(
              _i8.Stream<String>.empty(),
            ),
          )
          as _i8.Future<_i8.Stream<String>>);

  @override
  _i8.Future<_i8.Stream<String>> myFetchWebText(INPUT_TYPE? criteria) =>
      (super.noSuchMethod(
            Invocation.method(#myFetchWebText, [criteria]),
            returnValue: _i8.Future<_i8.Stream<String>>.value(
              _i8.Stream<String>.empty(),
            ),
            returnValueForMissingStub: _i8.Future<_i8.Stream<String>>.value(
              _i8.Stream<String>.empty(),
            ),
          )
          as _i8.Future<_i8.Stream<String>>);

  @override
  String myDataSourceName() =>
      (super.noSuchMethod(
            Invocation.method(#myDataSourceName, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#myDataSourceName, []),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#myDataSourceName, []),
            ),
          )
          as String);

  @override
  _i7.DataSourceFn myOfflineData() =>
      (super.noSuchMethod(
            Invocation.method(#myOfflineData, []),
            returnValue: (dynamic s) => _i8.Future<_i8.Stream<String>>.value(
              _i8.Stream<String>.empty(),
            ),
            returnValueForMissingStub: (dynamic s) =>
                _i8.Future<_i8.Stream<String>>.value(
                  _i8.Stream<String>.empty(),
                ),
          )
          as _i7.DataSourceFn);

  @override
  OUTPUT_TYPE myYieldError(String? contents) =>
      (super.noSuchMethod(
            Invocation.method(#myYieldError, [contents]),
            returnValue: _i5.dummyValue<OUTPUT_TYPE>(
              this,
              Invocation.method(#myYieldError, [contents]),
            ),
            returnValueForMissingStub: _i5.dummyValue<OUTPUT_TYPE>(
              this,
              Invocation.method(#myYieldError, [contents]),
            ),
          )
          as OUTPUT_TYPE);

  @override
  Uri myConstructURI(String? searchCriteria, {int? pageNumber = 1}) =>
      (super.noSuchMethod(
            Invocation.method(
              #myConstructURI,
              [searchCriteria],
              {#pageNumber: pageNumber},
            ),
            returnValue: _FakeUri_1(
              this,
              Invocation.method(
                #myConstructURI,
                [searchCriteria],
                {#pageNumber: pageNumber},
              ),
            ),
            returnValueForMissingStub: _FakeUri_1(
              this,
              Invocation.method(
                #myConstructURI,
                [searchCriteria],
                {#pageNumber: pageNumber},
              ),
            ),
          )
          as Uri);

  @override
  String myFormatInputAsText() =>
      (super.noSuchMethod(
            Invocation.method(#myFormatInputAsText, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#myFormatInputAsText, []),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#myFormatInputAsText, []),
            ),
          )
          as String);

  @override
  String myFormatInputAsAddress() =>
      (super.noSuchMethod(
            Invocation.method(#myFormatInputAsAddress, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#myFormatInputAsAddress, []),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#myFormatInputAsAddress, []),
            ),
          )
          as String);

  @override
  int myGetPageNumber() =>
      (super.noSuchMethod(
            Invocation.method(#myGetPageNumber, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void myConstructHeaders(_i3.HttpHeaders? headers) => super.noSuchMethod(
    Invocation.method(#myConstructHeaders, [headers]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> myIsResultCached() =>
      (super.noSuchMethod(
            Invocation.method(#myIsResultCached, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  bool myIsCacheStale() =>
      (super.noSuchMethod(
            Invocation.method(#myIsCacheStale, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> myAddResultToCache(OUTPUT_TYPE? fetchedResult) =>
      (super.noSuchMethod(
            Invocation.method(#myAddResultToCache, [fetchedResult]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> myClearCache() =>
      (super.noSuchMethod(
            Invocation.method(#myClearCache, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<String>? myHttpError(
    Uri? address,
    int? statusCode,
    _i3.HttpClientResponse? response,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#myHttpError, [address, statusCode, response]),
            returnValueForMissingStub: null,
          )
          as _i8.Stream<String>?);

  @override
  List<OUTPUT_TYPE> myFetchResultFromCache() =>
      (super.noSuchMethod(
            Invocation.method(#myFetchResultFromCache, []),
            returnValue: <OUTPUT_TYPE>[],
            returnValueForMissingStub: <OUTPUT_TYPE>[],
          )
          as List<OUTPUT_TYPE>);

  @override
  _i8.Stream<OUTPUT_TYPE> baseTransform() =>
      (super.noSuchMethod(
            Invocation.method(#baseTransform, []),
            returnValue: _i8.Stream<OUTPUT_TYPE>.empty(),
            returnValueForMissingStub: _i8.Stream<OUTPUT_TYPE>.empty(),
          )
          as _i8.Stream<OUTPUT_TYPE>);

  @override
  _i8.Stream<String> baseConvertCriteriaToWebText() =>
      (super.noSuchMethod(
            Invocation.method(#baseConvertCriteriaToWebText, []),
            returnValue: _i8.Stream<String>.empty(),
            returnValueForMissingStub: _i8.Stream<String>.empty(),
          )
          as _i8.Stream<String>);

  @override
  _i8.Stream<dynamic> baseConvertWebTextToTraversableTree(
    _i8.Stream<String>? webStream,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#baseConvertWebTextToTraversableTree, [
              webStream,
            ]),
            returnValue: _i8.Stream<dynamic>.empty(),
            returnValueForMissingStub: _i8.Stream<dynamic>.empty(),
          )
          as _i8.Stream<dynamic>);

  @override
  _i8.Stream<OUTPUT_TYPE> baseConvertTreeToOutputType(
    _i8.Stream<dynamic>? pageMap,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#baseConvertTreeToOutputType, [pageMap]),
            returnValue: _i8.Stream<OUTPUT_TYPE>.empty(),
            returnValueForMissingStub: _i8.Stream<OUTPUT_TYPE>.empty(),
          )
          as _i8.Stream<OUTPUT_TYPE>);

  @override
  Iterable<OUTPUT_TYPE> myMergeOutputType(Iterable<OUTPUT_TYPE>? output) =>
      (super.noSuchMethod(
            Invocation.method(#myMergeOutputType, [output]),
            returnValue: <OUTPUT_TYPE>[],
            returnValueForMissingStub: <OUTPUT_TYPE>[],
          )
          as Iterable<OUTPUT_TYPE>);

  @override
  _i8.Future<_i8.Stream<OUTPUT_TYPE>> baseYieldFetchedObjects({
    _i7.DataSourceFn? source,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#baseYieldFetchedObjects, [], {#source: source}),
            returnValue: _i8.Future<_i8.Stream<OUTPUT_TYPE>>.value(
              _i8.Stream<OUTPUT_TYPE>.empty(),
            ),
            returnValueForMissingStub:
                _i8.Future<_i8.Stream<OUTPUT_TYPE>>.value(
                  _i8.Stream<OUTPUT_TYPE>.empty(),
                ),
          )
          as _i8.Future<_i8.Stream<OUTPUT_TYPE>>);

  @override
  _i8.Future<_i8.Stream<String>> baseFetchWebText(dynamic criteria) =>
      (super.noSuchMethod(
            Invocation.method(#baseFetchWebText, [criteria]),
            returnValue: _i8.Future<_i8.Stream<String>>.value(
              _i8.Stream<String>.empty(),
            ),
            returnValueForMissingStub: _i8.Future<_i8.Stream<String>>.value(
              _i8.Stream<String>.empty(),
            ),
          )
          as _i8.Future<_i8.Stream<String>>);

  @override
  String baseConstructErrorMessage(String? context, dynamic error) =>
      (super.noSuchMethod(
            Invocation.method(#baseConstructErrorMessage, [context, error]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#baseConstructErrorMessage, [context, error]),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#baseConstructErrorMessage, [context, error]),
            ),
          )
          as String);

  @override
  _i3.HttpClient baseGetHttpClient() =>
      (super.noSuchMethod(
            Invocation.method(#baseGetHttpClient, []),
            returnValue: _FakeHttpClient_2(
              this,
              Invocation.method(#baseGetHttpClient, []),
            ),
            returnValueForMissingStub: _FakeHttpClient_2(
              this,
              Invocation.method(#baseGetHttpClient, []),
            ),
          )
          as _i3.HttpClient);
}
