// Mocks generated by Mockito from annotations
// in my_movie_search/test/unit/mmsnav_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i9;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:flutter_custom_tabs/flutter_custom_tabs.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:my_movie_search/persistence/firebase/firebase_common.dart'
    as _i7;
import 'package:my_movie_search/persistence/nav_log.dart' as _i10;
import 'package:my_movie_search/utilities/navigation/app_context.dart' as _i11;
import 'package:my_movie_search/utilities/navigation/route_info.dart' as _i6;
import 'package:my_movie_search/utilities/navigation/web_nav.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWidget_0 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeInheritedWidget_1 extends _i1.SmartFake
    implements _i2.InheritedWidget {
  _FakeInheritedWidget_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDiagnosticsNode_2 extends _i1.SmartFake
    implements _i3.DiagnosticsNode {
  _FakeDiagnosticsNode_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({
    _i3.TextTreeConfiguration? parentConfiguration,
    _i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info,
  }) => super.toString();
}

/// A class which mocks [MMSFlutterCanvas].
///
/// See the documentation for Mockito's code generation for more information.
class MockMMSFlutterCanvas extends _i1.Mock implements _i4.MMSFlutterCanvas {
  @override
  _i5.Future<Object?> viewWebPage(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#viewWebPage, [url]),
            returnValue: _i5.Future<Object?>.value(),
            returnValueForMissingStub: _i5.Future<Object?>.value(),
          )
          as _i5.Future<Object?>);

  @override
  _i5.Future<Object?> viewFlutterPage(
    _i6.RouteInfo? page, {
    bool? showKeyboardOnReturn = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #viewFlutterPage,
              [page],
              {#showKeyboardOnReturn: showKeyboardOnReturn},
            ),
            returnValue: _i5.Future<Object?>.value(),
            returnValueForMissingStub: _i5.Future<Object?>.value(),
          )
          as _i5.Future<Object?>);

  @override
  _i5.Future<Object?> viewFlutterRootPage(_i6.RouteInfo? page) =>
      (super.noSuchMethod(
            Invocation.method(#viewFlutterRootPage, [page]),
            returnValue: _i5.Future<Object?>.value(),
            returnValueForMissingStub: _i5.Future<Object?>.value(),
          )
          as _i5.Future<Object?>);

  @override
  bool closeCurrentScreen() =>
      (super.noSuchMethod(
            Invocation.method(#closeCurrentScreen, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<String?>? getInput(String? title, String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#getInput, [title, prompt]),
            returnValueForMissingStub: null,
          )
          as _i5.Future<String?>?);
}

/// A class which mocks [FirebaseApplicationState].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseApplicationState extends _i1.Mock
    implements _i7.FirebaseApplicationState {
  @override
  _i5.Future<bool> get loggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#loggedIn),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  set loggedIn(_i5.Future<bool>? value) => super.noSuchMethod(
    Invocation.setter(#loggedIn, value),
    returnValueForMissingStub: null,
  );

  @override
  set userDisplayName(String? value) => super.noSuchMethod(
    Invocation.setter(#userDisplayName, value),
    returnValueForMissingStub: null,
  );

  @override
  set userId(String? value) => super.noSuchMethod(
    Invocation.setter(#userId, value),
    returnValueForMissingStub: null,
  );

  @override
  set deviceType(String? value) => super.noSuchMethod(
    Invocation.setter(#deviceType, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> login() =>
      (super.noSuchMethod(
            Invocation.method(#login, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> platformLogin() =>
      (super.noSuchMethod(
            Invocation.method(#platformLogin, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Object?> fetchRecord(
    String? collectionPath, {
    required String? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRecord, [collectionPath], {#id: id}),
            returnValue: _i5.Future<Object?>.value(),
            returnValueForMissingStub: _i5.Future<Object?>.value(),
          )
          as _i5.Future<Object?>);

  @override
  _i5.Stream<Object?> fetchRecords(
    String? collectionPath, {
    String? filterFieldPath,
    Object? isEqualTo,
    Object? isNotEqualTo,
    Object? isLessThan,
    Object? isLessThanOrEqualTo,
    Object? isGreaterThan,
    Object? isGreaterThanOrEqualTo,
    Object? arrayContains,
    List<Object?>? arrayContainsAny,
    List<Object?>? whereIn,
    List<Object?>? whereNotIn,
    bool? isNull = false,
    _i5.Completer<bool>? initalDataLoadComplete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchRecords,
              [collectionPath],
              {
                #filterFieldPath: filterFieldPath,
                #isEqualTo: isEqualTo,
                #isNotEqualTo: isNotEqualTo,
                #isLessThan: isLessThan,
                #isLessThanOrEqualTo: isLessThanOrEqualTo,
                #isGreaterThan: isGreaterThan,
                #isGreaterThanOrEqualTo: isGreaterThanOrEqualTo,
                #arrayContains: arrayContains,
                #arrayContainsAny: arrayContainsAny,
                #whereIn: whereIn,
                #whereNotIn: whereNotIn,
                #isNull: isNull,
                #initalDataLoadComplete: initalDataLoadComplete,
              },
            ),
            returnValue: _i5.Stream<Object?>.empty(),
            returnValueForMissingStub: _i5.Stream<Object?>.empty(),
          )
          as _i5.Stream<Object?>);

  @override
  _i5.Future<Object?>? addRecord(
    String? collectionPath, {
    String? message,
    String? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addRecord,
              [collectionPath],
              {#message: message, #id: id},
            ),
            returnValueForMissingStub: null,
          )
          as _i5.Future<Object?>?);

  @override
  Map<String, Object?> newRecord(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#newRecord, [message]),
            returnValue: <String, Object?>{},
            returnValueForMissingStub: <String, Object?>{},
          )
          as Map<String, Object?>);

  @override
  String derivedUser(String? device) =>
      (super.noSuchMethod(
            Invocation.method(#derivedUser, [device]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#derivedUser, [device]),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#derivedUser, [device]),
            ),
          )
          as String);

  @override
  bool derivedUserMatch(String? device, Object? devices) =>
      (super.noSuchMethod(
            Invocation.method(#derivedUserMatch, [device, devices]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavLog].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavLog extends _i1.Mock implements _i10.NavLog {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void logPageOpen(_i6.RouteInfo? route) => super.noSuchMethod(
    Invocation.method(#logPageOpen, [route]),
    returnValueForMissingStub: null,
  );

  @override
  void logPageClose(_i6.RouteInfo? route) => super.noSuchMethod(
    Invocation.method(#logPageClose, [route]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppNavigator extends _i1.Mock implements _i11.AppNavigator {
  @override
  _i5.Future<T?> pushNamed<T extends Object?>(String? name, {Object? extra}) =>
      (super.noSuchMethod(
            Invocation.method(#pushNamed, [name], {#extra: extra}),
            returnValue: _i5.Future<T?>.value(),
            returnValueForMissingStub: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  void pushReplacementNamed<T extends Object?>(String? name, {Object? extra}) =>
      super.noSuchMethod(
        Invocation.method(#pushReplacementNamed, [name], {#extra: extra}),
        returnValueForMissingStub: null,
      );

  @override
  bool pop<T extends Object?>([T? result]) =>
      (super.noSuchMethod(
            Invocation.method(#pop, [result]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [AppTheme].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppTheme extends _i1.Mock implements _i11.AppTheme {}

/// A class which mocks [AppDialogs].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDialogs extends _i1.Mock implements _i11.AppDialogs {
  @override
  _i5.Future<Object?> popup(String? dialogText, String? title) =>
      (super.noSuchMethod(
            Invocation.method(#popup, [dialogText, title]),
            returnValue: _i5.Future<Object?>.value(),
            returnValueForMissingStub: _i5.Future<Object?>.value(),
          )
          as _i5.Future<Object?>);

  @override
  _i5.Future<String?> inputPopup(String? dialogText, String? title) =>
      (super.noSuchMethod(
            Invocation.method(#inputPopup, [dialogText, title]),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);
}

/// A class which mocks [AppFocus].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppFocus extends _i1.Mock implements _i11.AppFocus {}

/// A class which mocks [CustomTabsLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomTabsLauncher extends _i1.Mock
    implements _i11.CustomTabsLauncher {
  @override
  _i5.Future<void> launch(
    String? url, {
    _i12.CustomTabsOptions? customTabsOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #launch,
              [url],
              {#customTabsOptions: customTabsOptions},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [BuildContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildContext extends _i1.Mock implements _i2.BuildContext {
  @override
  _i2.Widget get widget =>
      (super.noSuchMethod(
            Invocation.getter(#widget),
            returnValue: _FakeWidget_0(this, Invocation.getter(#widget)),
            returnValueForMissingStub: _FakeWidget_0(
              this,
              Invocation.getter(#widget),
            ),
          )
          as _i2.Widget);

  @override
  bool get mounted =>
      (super.noSuchMethod(
            Invocation.getter(#mounted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get debugDoingBuild =>
      (super.noSuchMethod(
            Invocation.getter(#debugDoingBuild),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.InheritedWidget dependOnInheritedElement(
    _i2.InheritedElement? ancestor, {
    Object? aspect,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #dependOnInheritedElement,
              [ancestor],
              {#aspect: aspect},
            ),
            returnValue: _FakeInheritedWidget_1(
              this,
              Invocation.method(
                #dependOnInheritedElement,
                [ancestor],
                {#aspect: aspect},
              ),
            ),
            returnValueForMissingStub: _FakeInheritedWidget_1(
              this,
              Invocation.method(
                #dependOnInheritedElement,
                [ancestor],
                {#aspect: aspect},
              ),
            ),
          )
          as _i2.InheritedWidget);

  @override
  void visitAncestorElements(_i2.ConditionalElementVisitor? visitor) =>
      super.noSuchMethod(
        Invocation.method(#visitAncestorElements, [visitor]),
        returnValueForMissingStub: null,
      );

  @override
  void visitChildElements(_i2.ElementVisitor? visitor) => super.noSuchMethod(
    Invocation.method(#visitChildElements, [visitor]),
    returnValueForMissingStub: null,
  );

  @override
  void dispatchNotification(_i2.Notification? notification) =>
      super.noSuchMethod(
        Invocation.method(#dispatchNotification, [notification]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.DiagnosticsNode describeElement(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#describeElement, [name], {#style: style}),
            returnValue: _FakeDiagnosticsNode_2(
              this,
              Invocation.method(#describeElement, [name], {#style: style}),
            ),
            returnValueForMissingStub: _FakeDiagnosticsNode_2(
              this,
              Invocation.method(#describeElement, [name], {#style: style}),
            ),
          )
          as _i3.DiagnosticsNode);

  @override
  _i3.DiagnosticsNode describeWidget(
    String? name, {
    _i3.DiagnosticsTreeStyle? style = _i3.DiagnosticsTreeStyle.errorProperty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#describeWidget, [name], {#style: style}),
            returnValue: _FakeDiagnosticsNode_2(
              this,
              Invocation.method(#describeWidget, [name], {#style: style}),
            ),
            returnValueForMissingStub: _FakeDiagnosticsNode_2(
              this,
              Invocation.method(#describeWidget, [name], {#style: style}),
            ),
          )
          as _i3.DiagnosticsNode);

  @override
  List<_i3.DiagnosticsNode> describeMissingAncestor({
    required Type? expectedAncestorType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#describeMissingAncestor, [], {
              #expectedAncestorType: expectedAncestorType,
            }),
            returnValue: <_i3.DiagnosticsNode>[],
            returnValueForMissingStub: <_i3.DiagnosticsNode>[],
          )
          as List<_i3.DiagnosticsNode>);

  @override
  _i3.DiagnosticsNode describeOwnershipChain(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#describeOwnershipChain, [name]),
            returnValue: _FakeDiagnosticsNode_2(
              this,
              Invocation.method(#describeOwnershipChain, [name]),
            ),
            returnValueForMissingStub: _FakeDiagnosticsNode_2(
              this,
              Invocation.method(#describeOwnershipChain, [name]),
            ),
          )
          as _i3.DiagnosticsNode);
}
