// Mocks generated by Mockito 5.4.6 from annotations
// in my_movie_search/test/unit/web_resource_interceptor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i2;
import 'dart:ui' as _i8;

import 'package:flutter_inappwebview/src/in_app_webview/headless_in_app_webview.dart'
    as _i7;
import 'package:flutter_inappwebview_platform_interface/flutter_inappwebview_platform_interface.dart'
    as _i4;
import 'package:flutter_inappwebview_platform_interface/src/web_uri.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientRequest_1 extends _i1.SmartFake
    implements _i2.HttpClientRequest {
  _FakeHttpClientRequest_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebUri_2 extends _i1.SmartFake implements _i3.WebUri {
  _FakeWebUri_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_3 extends _i1.SmartFake implements Uri {
  _FakeUri_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlatformHeadlessInAppWebView_4 extends _i1.SmartFake
    implements _i4.PlatformHeadlessInAppWebView {
  _FakePlatformHeadlessInAppWebView_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i2.HttpClient {
  @override
  Duration get idleTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#idleTimeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#idleTimeout)),
            returnValueForMissingStub: _FakeDuration_0(
              this,
              Invocation.getter(#idleTimeout),
            ),
          )
          as Duration);

  @override
  bool get autoUncompress =>
      (super.noSuchMethod(
            Invocation.getter(#autoUncompress),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set idleTimeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#idleTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set connectionTimeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#connectionTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set maxConnectionsPerHost(int? value) => super.noSuchMethod(
    Invocation.setter(#maxConnectionsPerHost, value),
    returnValueForMissingStub: null,
  );

  @override
  set autoUncompress(bool? value) => super.noSuchMethod(
    Invocation.setter(#autoUncompress, value),
    returnValueForMissingStub: null,
  );

  @override
  set userAgent(String? value) => super.noSuchMethod(
    Invocation.setter(#userAgent, value),
    returnValueForMissingStub: null,
  );

  @override
  set authenticate(_i5.Future<bool> Function(Uri, String, String?)? f) =>
      super.noSuchMethod(
        Invocation.setter(#authenticate, f),
        returnValueForMissingStub: null,
      );

  @override
  set connectionFactory(
    _i5.Future<_i2.ConnectionTask<_i2.Socket>> Function(Uri, String?, int?)? f,
  ) => super.noSuchMethod(
    Invocation.setter(#connectionFactory, f),
    returnValueForMissingStub: null,
  );

  @override
  set findProxy(String Function(Uri)? f) => super.noSuchMethod(
    Invocation.setter(#findProxy, f),
    returnValueForMissingStub: null,
  );

  @override
  set authenticateProxy(
    _i5.Future<bool> Function(String, int, String, String?)? f,
  ) => super.noSuchMethod(
    Invocation.setter(#authenticateProxy, f),
    returnValueForMissingStub: null,
  );

  @override
  set badCertificateCallback(
    bool Function(_i2.X509Certificate, String, int)? callback,
  ) => super.noSuchMethod(
    Invocation.setter(#badCertificateCallback, callback),
    returnValueForMissingStub: null,
  );

  @override
  set keyLog(dynamic Function(String)? callback) => super.noSuchMethod(
    Invocation.setter(#keyLog, callback),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.HttpClientRequest> open(
    String? method,
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#open, [method, host, port, path]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#open, [method, host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#open, [method, host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> openUrl(String? method, Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#openUrl, [method, url]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#openUrl, [method, url]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#openUrl, [method, url]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> get(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#get, [host, port, path]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#get, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#get, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> getUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#getUrl, [url]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(this, Invocation.method(#getUrl, [url])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(this, Invocation.method(#getUrl, [url])),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> post(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#post, [host, port, path]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#post, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#post, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> postUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#postUrl, [url]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#postUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#postUrl, [url]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> put(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#put, [host, port, path]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#put, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#put, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> putUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#putUrl, [url]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(this, Invocation.method(#putUrl, [url])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(this, Invocation.method(#putUrl, [url])),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> delete(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [host, port, path]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#delete, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#delete, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> deleteUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUrl, [url]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#deleteUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#deleteUrl, [url]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> patch(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patch, [host, port, path]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#patch, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#patch, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> patchUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#patchUrl, [url]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#patchUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#patchUrl, [url]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> head(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#head, [host, port, path]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#head, [host, port, path]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#head, [host, port, path]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  _i5.Future<_i2.HttpClientRequest> headUrl(Uri? url) =>
      (super.noSuchMethod(
            Invocation.method(#headUrl, [url]),
            returnValue: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#headUrl, [url]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.HttpClientRequest>.value(
              _FakeHttpClientRequest_1(
                this,
                Invocation.method(#headUrl, [url]),
              ),
            ),
          )
          as _i5.Future<_i2.HttpClientRequest>);

  @override
  void addCredentials(
    Uri? url,
    String? realm,
    _i2.HttpClientCredentials? credentials,
  ) => super.noSuchMethod(
    Invocation.method(#addCredentials, [url, realm, credentials]),
    returnValueForMissingStub: null,
  );

  @override
  void addProxyCredentials(
    String? host,
    int? port,
    String? realm,
    _i2.HttpClientCredentials? credentials,
  ) => super.noSuchMethod(
    Invocation.method(#addProxyCredentials, [host, port, realm, credentials]),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HttpHeaders].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpHeaders extends _i1.Mock implements _i2.HttpHeaders {
  @override
  int get contentLength =>
      (super.noSuchMethod(
            Invocation.getter(#contentLength),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get persistentConnection =>
      (super.noSuchMethod(
            Invocation.getter(#persistentConnection),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get chunkedTransferEncoding =>
      (super.noSuchMethod(
            Invocation.getter(#chunkedTransferEncoding),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set date(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#date, value),
    returnValueForMissingStub: null,
  );

  @override
  set expires(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#expires, value),
    returnValueForMissingStub: null,
  );

  @override
  set ifModifiedSince(DateTime? value) => super.noSuchMethod(
    Invocation.setter(#ifModifiedSince, value),
    returnValueForMissingStub: null,
  );

  @override
  set host(String? value) => super.noSuchMethod(
    Invocation.setter(#host, value),
    returnValueForMissingStub: null,
  );

  @override
  set port(int? value) => super.noSuchMethod(
    Invocation.setter(#port, value),
    returnValueForMissingStub: null,
  );

  @override
  set contentType(_i2.ContentType? value) => super.noSuchMethod(
    Invocation.setter(#contentType, value),
    returnValueForMissingStub: null,
  );

  @override
  set contentLength(int? value) => super.noSuchMethod(
    Invocation.setter(#contentLength, value),
    returnValueForMissingStub: null,
  );

  @override
  set persistentConnection(bool? value) => super.noSuchMethod(
    Invocation.setter(#persistentConnection, value),
    returnValueForMissingStub: null,
  );

  @override
  set chunkedTransferEncoding(bool? value) => super.noSuchMethod(
    Invocation.setter(#chunkedTransferEncoding, value),
    returnValueForMissingStub: null,
  );

  @override
  List<String>? operator [](String? name) =>
      (super.noSuchMethod(
            Invocation.method(#[], [name]),
            returnValueForMissingStub: null,
          )
          as List<String>?);

  @override
  String? value(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#value, [name]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  void add(String? name, Object? value, {bool? preserveHeaderCase = false}) =>
      super.noSuchMethod(
        Invocation.method(
          #add,
          [name, value],
          {#preserveHeaderCase: preserveHeaderCase},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void set(String? name, Object? value, {bool? preserveHeaderCase = false}) =>
      super.noSuchMethod(
        Invocation.method(
          #set,
          [name, value],
          {#preserveHeaderCase: preserveHeaderCase},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void remove(String? name, Object? value) => super.noSuchMethod(
    Invocation.method(#remove, [name, value]),
    returnValueForMissingStub: null,
  );

  @override
  void removeAll(String? name) => super.noSuchMethod(
    Invocation.method(#removeAll, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void forEach(void Function(String, List<String>)? action) =>
      super.noSuchMethod(
        Invocation.method(#forEach, [action]),
        returnValueForMissingStub: null,
      );

  @override
  void noFolding(String? name) => super.noSuchMethod(
    Invocation.method(#noFolding, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WebResourceRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebResourceRequest extends _i1.Mock
    implements _i4.WebResourceRequest {
  @override
  _i3.WebUri get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _FakeWebUri_2(this, Invocation.getter(#url)),
            returnValueForMissingStub: _FakeWebUri_2(
              this,
              Invocation.getter(#url),
            ),
          )
          as _i3.WebUri);

  @override
  set hasGesture(bool? value) => super.noSuchMethod(
    Invocation.setter(#hasGesture, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#headers, value),
    returnValueForMissingStub: null,
  );

  @override
  set isForMainFrame(bool? value) => super.noSuchMethod(
    Invocation.setter(#isForMainFrame, value),
    returnValueForMissingStub: null,
  );

  @override
  set isRedirect(bool? value) => super.noSuchMethod(
    Invocation.setter(#isRedirect, value),
    returnValueForMissingStub: null,
  );

  @override
  set method(String? value) => super.noSuchMethod(
    Invocation.setter(#method, value),
    returnValueForMissingStub: null,
  );

  @override
  set url(_i3.WebUri? value) => super.noSuchMethod(
    Invocation.setter(#url, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(
            Invocation.method(#toMap, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [WebUri].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebUri extends _i1.Mock implements _i3.WebUri {
  @override
  bool get forceToStringRawValue =>
      (super.noSuchMethod(
            Invocation.getter(#forceToStringRawValue),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get rawValue =>
      (super.noSuchMethod(
            Invocation.getter(#rawValue),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#rawValue),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#rawValue),
            ),
          )
          as String);

  @override
  Uri get uriValue =>
      (super.noSuchMethod(
            Invocation.getter(#uriValue),
            returnValue: _FakeUri_3(this, Invocation.getter(#uriValue)),
            returnValueForMissingStub: _FakeUri_3(
              this,
              Invocation.getter(#uriValue),
            ),
          )
          as Uri);

  @override
  bool get isValidUri =>
      (super.noSuchMethod(
            Invocation.getter(#isValidUri),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get authority =>
      (super.noSuchMethod(
            Invocation.getter(#authority),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#authority),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#authority),
            ),
          )
          as String);

  @override
  String get fragment =>
      (super.noSuchMethod(
            Invocation.getter(#fragment),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#fragment),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#fragment),
            ),
          )
          as String);

  @override
  bool get hasAbsolutePath =>
      (super.noSuchMethod(
            Invocation.getter(#hasAbsolutePath),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasAuthority =>
      (super.noSuchMethod(
            Invocation.getter(#hasAuthority),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasEmptyPath =>
      (super.noSuchMethod(
            Invocation.getter(#hasEmptyPath),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasFragment =>
      (super.noSuchMethod(
            Invocation.getter(#hasFragment),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasPort =>
      (super.noSuchMethod(
            Invocation.getter(#hasPort),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasQuery =>
      (super.noSuchMethod(
            Invocation.getter(#hasQuery),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasScheme =>
      (super.noSuchMethod(
            Invocation.getter(#hasScheme),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get host =>
      (super.noSuchMethod(
            Invocation.getter(#host),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#host)),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#host),
            ),
          )
          as String);

  @override
  bool get isAbsolute =>
      (super.noSuchMethod(
            Invocation.getter(#isAbsolute),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get origin =>
      (super.noSuchMethod(
            Invocation.getter(#origin),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#origin),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#origin),
            ),
          )
          as String);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#path)),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  List<String> get pathSegments =>
      (super.noSuchMethod(
            Invocation.getter(#pathSegments),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  int get port =>
      (super.noSuchMethod(
            Invocation.getter(#port),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get query =>
      (super.noSuchMethod(
            Invocation.getter(#query),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#query),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#query),
            ),
          )
          as String);

  @override
  Map<String, String> get queryParameters =>
      (super.noSuchMethod(
            Invocation.getter(#queryParameters),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, List<String>> get queryParametersAll =>
      (super.noSuchMethod(
            Invocation.getter(#queryParametersAll),
            returnValue: <String, List<String>>{},
            returnValueForMissingStub: <String, List<String>>{},
          )
          as Map<String, List<String>>);

  @override
  String get scheme =>
      (super.noSuchMethod(
            Invocation.getter(#scheme),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#scheme),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#scheme),
            ),
          )
          as String);

  @override
  String get userInfo =>
      (super.noSuchMethod(
            Invocation.getter(#userInfo),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#userInfo),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#userInfo),
            ),
          )
          as String);

  @override
  set forceToStringRawValue(bool? value) => super.noSuchMethod(
    Invocation.setter(#forceToStringRawValue, value),
    returnValueForMissingStub: null,
  );

  @override
  bool isScheme(String? scheme) =>
      (super.noSuchMethod(
            Invocation.method(#isScheme, [scheme]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Uri normalizePath() =>
      (super.noSuchMethod(
            Invocation.method(#normalizePath, []),
            returnValue: _FakeUri_3(
              this,
              Invocation.method(#normalizePath, []),
            ),
            returnValueForMissingStub: _FakeUri_3(
              this,
              Invocation.method(#normalizePath, []),
            ),
          )
          as Uri);

  @override
  Uri removeFragment() =>
      (super.noSuchMethod(
            Invocation.method(#removeFragment, []),
            returnValue: _FakeUri_3(
              this,
              Invocation.method(#removeFragment, []),
            ),
            returnValueForMissingStub: _FakeUri_3(
              this,
              Invocation.method(#removeFragment, []),
            ),
          )
          as Uri);

  @override
  Uri replace({
    String? scheme,
    String? userInfo,
    String? host,
    int? port,
    String? path,
    Iterable<String>? pathSegments,
    String? query,
    Map<String, dynamic>? queryParameters,
    String? fragment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replace, [], {
              #scheme: scheme,
              #userInfo: userInfo,
              #host: host,
              #port: port,
              #path: path,
              #pathSegments: pathSegments,
              #query: query,
              #queryParameters: queryParameters,
              #fragment: fragment,
            }),
            returnValue: _FakeUri_3(
              this,
              Invocation.method(#replace, [], {
                #scheme: scheme,
                #userInfo: userInfo,
                #host: host,
                #port: port,
                #path: path,
                #pathSegments: pathSegments,
                #query: query,
                #queryParameters: queryParameters,
                #fragment: fragment,
              }),
            ),
            returnValueForMissingStub: _FakeUri_3(
              this,
              Invocation.method(#replace, [], {
                #scheme: scheme,
                #userInfo: userInfo,
                #host: host,
                #port: port,
                #path: path,
                #pathSegments: pathSegments,
                #query: query,
                #queryParameters: queryParameters,
                #fragment: fragment,
              }),
            ),
          )
          as Uri);

  @override
  Uri resolve(String? reference) =>
      (super.noSuchMethod(
            Invocation.method(#resolve, [reference]),
            returnValue: _FakeUri_3(
              this,
              Invocation.method(#resolve, [reference]),
            ),
            returnValueForMissingStub: _FakeUri_3(
              this,
              Invocation.method(#resolve, [reference]),
            ),
          )
          as Uri);

  @override
  Uri resolveUri(Uri? reference) =>
      (super.noSuchMethod(
            Invocation.method(#resolveUri, [reference]),
            returnValue: _FakeUri_3(
              this,
              Invocation.method(#resolveUri, [reference]),
            ),
            returnValueForMissingStub: _FakeUri_3(
              this,
              Invocation.method(#resolveUri, [reference]),
            ),
          )
          as Uri);

  @override
  String toFilePath({bool? windows}) =>
      (super.noSuchMethod(
            Invocation.method(#toFilePath, [], {#windows: windows}),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#toFilePath, [], {#windows: windows}),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.method(#toFilePath, [], {#windows: windows}),
            ),
          )
          as String);
}

/// A class which mocks [HeadlessInAppWebView].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeadlessInAppWebView extends _i1.Mock
    implements _i7.HeadlessInAppWebView {
  @override
  _i4.PlatformHeadlessInAppWebView get platform =>
      (super.noSuchMethod(
            Invocation.getter(#platform),
            returnValue: _FakePlatformHeadlessInAppWebView_4(
              this,
              Invocation.getter(#platform),
            ),
            returnValueForMissingStub: _FakePlatformHeadlessInAppWebView_4(
              this,
              Invocation.getter(#platform),
            ),
          )
          as _i4.PlatformHeadlessInAppWebView);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  _i5.Future<void> run() =>
      (super.noSuchMethod(
            Invocation.method(#run, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isRunning() =>
      (super.noSuchMethod(
            Invocation.method(#isRunning, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setSize(_i8.Size? size) =>
      (super.noSuchMethod(
            Invocation.method(#setSize, [size]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i8.Size?> getSize() =>
      (super.noSuchMethod(
            Invocation.method(#getSize, []),
            returnValue: _i5.Future<_i8.Size?>.value(),
            returnValueForMissingStub: _i5.Future<_i8.Size?>.value(),
          )
          as _i5.Future<_i8.Size?>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
