// Mocks generated by Mockito 5.4.6 from annotations
// in my_movie_search/test/unit/web_headless_extractor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_movie_search/utilities/web_data/headless_web_engine.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HeadlessWebEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeadlessWebEngine extends _i1.Mock implements _i2.HeadlessWebEngine {
  @override
  _i3.Future<int> run({
    required String? url,
    required String? apiAcceptFilter,
    required _i2.DataCallback? onEngineData,
    _i2.PageLoadCallback? onPageLoaded,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#run, [], {
              #url: url,
              #apiAcceptFilter: apiAcceptFilter,
              #onEngineData: onEngineData,
              #onPageLoaded: onPageLoaded,
              #headers: headers,
            }),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<dynamic> evaluateJavascript(String? script) =>
      (super.noSuchMethod(
            Invocation.method(#evaluateJavascript, [script]),
            returnValue: _i3.Future<dynamic>.value(),
            returnValueForMissingStub: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<void> dispose({Duration? optionalDelay = Duration.zero}) =>
      (super.noSuchMethod(
            Invocation.method(#dispose, [], {#optionalDelay: optionalDelay}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
